import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function BlogDetail() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <img src="./logo.jpg" alt="" className={styles.logo} />
        <div className={styles.text}>
          <h1>blog id</h1>
          <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Qui, odio.
            Error earum iste repellendus asperiores repellat! Eveniet quisquam
            laudantium ipsam animi dolorem voluptas harum vel! Sequi, id nobis?
            Voluptate, fuga?
          </p>
        </div>
      </main>
    </>
  );
}
