import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import { Layout } from "@/components/layout";

const inter = Inter({ subsets: ["latin"] });

export default function AboutUs() {
  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className={styles.text}>
          <h1>Nosotros</h1>
          <p>
            Somos un equipo de expertos en creación de sitios web y desarrollo
            de tiendas en línea. Nos apasiona ayudar a nuestros clientes a
            alcanzar sus objetivos comerciales a través de la tecnología y la
            innovación.
          </p>
          <p></p>
          Nuestro equipo está compuesto por profesionales altamente capacitados
          y apasionados por su trabajo. Cada uno de nosotros posee habilidades
          únicas y complementarias, lo que nos permite ofrecer un servicio
          integral y de alta calidad a nuestros clientes.
          <p>Entre las habilidades técnicas de nuestro equipo se incluyen:</p>
          <ul>
            <li>
              Experiencia en el desarrollo de tiendas virtuales y aplicaciones
              en línea
            </li>
            <li>
              Conocimiento profundo de los sistemas de carritos de compra y la
              integración de pagos en línea
            </li>
            <li>
              Experiencia en la creación de landing pages y la optimización de
              la conversión
            </li>
            <li>
              Conocimiento avanzado de marketing digital y estrategias de
              marketing en línea
            </li>
            <li>Experiencia en la gestión de dominios y el alojamiento web</li>
            <li>
              Trabajar con nosotros significa tener acceso a un equipo de
              expertos en tecnología y marketing que están comprometidos con el
              éxito de su negocio. Nos esforzamos por entender sus necesidades y
              brindar un servicio personalizado y eficaz. Además, estamos
              comprometidos con la satisfacción total de nuestros clientes y
              trabajamos incansablemente para asegurarnos de que sus proyectos
              sean un éxito.
            </li>
          </ul>
          <p>
            Si está buscando un equipo confiable y experimentado para ayudarlo a
            llevar su negocio en línea, no busque más. Contáctenos hoy mismo
            para obtener más información sobre cómo podemos ayudarlo a alcanzar
            sus objetivos comerciales.
          </p>
        </div>
      </main>
    </Layout>
  );
}
