import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import { Layout } from "@/components/layout";

const inter = Inter({ subsets: ["latin"] });

export default function Price() {
  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <img src="./logo.jpg" alt="" className={styles.logo} />
        <div className={styles.text}>
          <h1>Precios</h1>
          <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Laborum
            necessitatibus assumenda recusandae, atque temporibus aliquam quidem
            doloribus placeat corrupti in itaque iste labore odio ab rem,
            dolorum quo dicta voluptate.
          </p>
        </div>
      </main>
    </Layout>
  );
}
